---
# Tasks for service account management

- name: "Create service account with proper metadata"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: "{{ ims_deployment_service_account }}"
        namespace: "{{ ims_deployment_namespace }}"
        labels: "{{ ims_deployment_labels | combine({
          'app.kubernetes.io/name': ims_deployment_app_name,
          'app.kubernetes.io/version': ims_deployment_app_version,
          'app.kubernetes.io/component': 'service-account'
        }) }}"
        annotations: "{{ ims_deployment_annotations | combine({
          'description': 'Service account for IMS connector with mainframe access'
        }) }}"
  register: ims_serviceaccount_result

- name: "Display service account creation status"
  ansible.builtin.debug:
    msg: |
      Service Account {{ ims_deployment_service_account }}: {{ 'Created' if ims_serviceaccount_result.changed else 'Already exists' }}
    verbosity: 1