---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vscode-server
  namespace: workshop-vscode
  labels:
    workshop.component: "vscode-server"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workshop-vscode-access
  labels:
    workshop.component: "vscode-server"
rules:
# Basic cluster read access for workshop exercises
- apiGroups: [""]
  resources: ["namespaces", "nodes", "persistentvolumes"]
  verbs: ["get", "list", "watch"]
# Access to workshop namespaces
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
  resourceNames: []
# AAP resources access
- apiGroups: ["apps", "extensions"]
  resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# Route access for workshop exercises
- apiGroups: ["route.openshift.io"]
  resources: ["routes"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# Image stream access
- apiGroups: ["image.openshift.io"]
  resources: ["imagestreams", "imagestreamtags"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# Template access
- apiGroups: ["template.openshift.io"]
  resources: ["templates", "templateinstances", "processedtemplates"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: workshop-vscode-access
  labels:
    workshop.component: "vscode-server"
subjects:
- kind: ServiceAccount
  name: vscode-server
  namespace: workshop-vscode
roleRef:
  kind: ClusterRole
  name: workshop-vscode-access
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workshop-namespace-admin
  namespace: workshop-aap
  labels:
    workshop.component: "vscode-server"
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vscode-workshop-admin
  namespace: workshop-aap
  labels:
    workshop.component: "vscode-server"
subjects:
- kind: ServiceAccount
  name: vscode-server
  namespace: workshop-vscode
roleRef:
  kind: Role
  name: workshop-namespace-admin
  apiGroup: rbac.authorization.k8s.io