---
# Tasks for creating service accounts

- name: "Create IMS service accounts with role-based configuration"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: "{{ item.name }}"
        namespace: "{{ ims_rbac_namespace }}"
        labels: "{{ ims_rbac_labels | combine({'workshop.redhat.com/role-type': item.role_type}) }}"
        annotations: "{{ ims_rbac_annotations | combine({
          'description': item.description,
          'workshop.redhat.com/created-for': ims_rbac_environment,
          'serviceaccount.openshift.io/oauth-redirecturi.first': 'https://oauth-openshift.apps.example.com/oauth/token/implicit'
        }) }}"
  loop: "{{ ims_rbac_service_accounts }}"
  when: item.environments is not defined or ims_rbac_environment in item.environments
  register: ims_service_accounts_result

- name: "Display service account creation status"
  ansible.builtin.debug:
    msg: |
      Service Account {{ item.item.name }}: {{ 'Created' if item.changed else 'Already exists' }}
  loop: "{{ ims_service_accounts_result.results }}"
  when: not item.skipped | default(false)
  loop_control:
    label: "{{ item.item.name if item.item is defined else 'N/A' }}"
  verbosity: 1