---
# Ansible Collections for AAP Workshop Execution Environment
# This file specifies all collections needed for the workshop exercises

collections:
  # Core Kubernetes/OpenShift integration
  - name: kubernetes.core
    version: ">=3.0.0"
  
  # OpenShift specific collection
  - name: redhat.openshift
    version: ">=2.0.0"
  
  # Community general collection (includes many useful modules)
  - name: community.general
    version: ">=7.0.0"
  
  # Community crypto collection (for certificate management)  
  - name: community.crypto
    version: ">=2.0.0"
  
  # POSIX collection (essential system modules)
  - name: ansible.posix
    version: ">=1.0.0"
  
  # Built-in collection (always included but explicit for clarity)
  - name: ansible.builtin
    version: ">=2.0.0"
  
  # Community Docker collection (for container operations)
  - name: community.docker
    version: ">=3.0.0"
  
  # Community OpenShift collection (additional OpenShift utilities)
  - name: community.okd
    version: ">=2.0.0"
  
  # Ansible Utils collection (for network and data processing)
  - name: ansible.utils
    version: ">=2.0.0"
  
  # Community Kubernetes collection (additional k8s utilities)
  - name: community.kubernetes
    version: ">=2.0.0"