---
# Ansible Collections for AAP Workshop Execution Environment
# This file specifies all collections needed for the workshop exercises
# Using specific version ranges to avoid version comparison issues

collections:
  # Core Kubernetes/OpenShift integration
  - name: kubernetes.core
    version: "3.0.1"
  
  # OpenShift specific collection
  - name: redhat.openshift
    version: "2.3.0"
  
  # Community general collection (includes many useful modules)
  - name: community.general
    version: "7.5.0"
  
  # Community crypto collection (for certificate management)  
  - name: community.crypto
    version: "2.17.0"
  
  # POSIX collection (essential system modules)
  - name: ansible.posix
    version: "1.5.4"
  
  # Built-in collection (always included but explicit for clarity)
  - name: ansible.builtin
    version: "2.16.0"
  
  # Community Docker collection (for container operations)
  - name: community.docker
    version: "3.4.11"
  
  # Community OpenShift collection (additional OpenShift utilities)
  - name: community.okd
    version: "2.3.0"
  
  # Ansible Utils collection (for network and data processing)
  - name: ansible.utils
    version: "2.12.0"
  
  # Community Kubernetes collection (additional k8s utilities)
  - name: community.kubernetes
    version: "2.0.1"