---
galaxy_info:
  author: Red Hat Workshop Team
  description: Role for managing IMS service accounts and RBAC in OpenShift
  company: Red Hat, Inc.
  license: Apache-2.0
  min_ansible_version: "2.12"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags:
    - openshift
    - kubernetes
    - rbac
    - security
    - ims
    - workshop

dependencies: []

collections:
  - kubernetes.core
  - redhat.openshift